# This script report needs more work to show formatted break dates.
#  Script:  breakPoint
#  Date:		07/16/2013
#  Imports observed time series or regression residuals and fits a LOWESS smoother to the time series data

#  Change points are identified using:
#	1.  Differenced time-series (identifies sudden changes, changes in datum)
#	2.  LOESS (identifies changes in slope from negative to positive)
#	3.  Moving window (identifies changes in the magnitude of the slope)

#################################################################
#REQUIRED PACKAGES

library("zoo")
library("timeSeries")
library("wq")
library("Kendall")
library("tseries")
library("epicalc")

require("lubridate")
require("zoo")
require("timeSeries")
require("wq")
require("Kendall")
require("tseries")
require("epicalc")

##############################################################
# FUNCTIONS
      
  fac2num <- function(x) as.numeric(as.character(x)); #function is present in S-plus but must be created for R

  # from USGS S-plus library function for confidence intervals
  pointwise = function(results.predict, coverage = 0.95){
        fit <- results.predict$fit
        limits <- qt(1. - (1. - coverage)/2., results.predict$df) * 
          results.predict$se.fit
        list(upper = fit + limits, fit = fit, lower = fit - limits)
      }

##############################################################
# BEGIN USER INPUT

file.path = "G:/Statistics/R/mydata/groundwater/"
file.name.orig <- "silverSpringsWells.csv"
destination.path <- "G:/Statistics/R/Output/breakPoint/"  # If JPEGs are generated by the script, they will be placed in this folder
alldata <- read.csv(paste(file.path, file.name.orig, sep = ""), header = TRUE)
start.date <- timeDate("01/01/1933")  # The script compares data after this date
end.date <- timeDate("01/01/2012")  # The script compares data before this date
  # mode defines the aggregation time-period: "D=Daily" "M=Month" "S=Season "Y=Yearly"
  # "D" may not be appropriate where the sampling frequency changesmode <- "M"
mode = "M"
column.label <- "Station"
tvar.label <- "date"    										# Column header in spreadsheet file for date
y.variable.label <- "value"									# Column header in spreadsheet file for value to be analyzed
y.label = "Level NAVD88" # Level NAVD88, Rainfall in, Discharge cfs
station.list <- "" #"Discharge_Silver River German"
exclude.stations <- c("")                   #  Stations to exclude from the analysis.  
  #  Stations may be excluded if they do not have enough seasonal data to
  #  perform the analysis, which results in an error in the seasonal child script

if(station.list == ""){
  eval(parse(text=paste("station.list <- unique(alldata$", column.label, ")", sep=""))) 
  if (exclude.stations[1] != "") {
    for (c in 1:length(exclude.stations)) {
      station.list <- station.list[station.list != exclude.stations[c]]
    }
  }
}

  scripts.path.name <- "G:/Statistics/R/Scripts/"
  station.list.char = as.character(station.list)
  data.0 <- alldata
  dataset.label <- column.label

#w = 4                                     # When debugging run the scipt for one station (Add } to end of script) 

for (w in 1:length(station.list.char)) {
  subset.label <- station.list.char[w]
  file.name <- paste(file.name.orig,as.character(station.list[w]))  # for chart labels
  station.list.char = as.character(station.list)
  data.0 <- alldata
  dataset.label <- column.label
  script.name <- "lowess"
  script.version <- "Version: USGS.SPLUS.R.VER1"
  scripts.path <- "G:/Statistics/R/Scripts/"


degree.x <- 1  #  If degree.x=1, linear fit.  degree.x=2, quadratic equation fit
span.1 <- 0.3  #  A smoothing parameter, which can be adjusted experimentally
span.2 <- 0.1  #  Second value for the smoothing parameter

  #  Parameters used to detect various break points
slope.change.window <- 5		# number of data points used to establish average slope
slope.change.factor <- 6.0		# factor used to detect change in slope (ratio of current slope to average slope)
slope.sd.factor		<- 4		# factor used to detect extreme changes in slope

  # date and offset allow user to set a fake point at which datum shifts by "offset"
break.date <- timeDate("01/01/1900")		# Set to less than start.date if want no bkpt
offset <- 0  				# For testing ability of the program to find a datum shift - should be set to zero for data analysis

  # SEASON DEFINITION 
  # seasons <- as.numeric(c(1,1,1,2,2,2,3,3,3,4,4,1))  # Used if mode is "S".  Can be changed to alter how months are grouped into seasons
seasons <- as.numeric(c(1,1,1,1,1,2,2,2,2,1,1,1))

  # Graphics Formatting Options
chart.option   <- 2        # option 0 produces no charts
chart.size.width  <- 6.0		# chart width for outer margins in inches
chart.size.height <- 6.0		# chart height for outer margins in inches 
legend.font.size  <- 0.75		# Legend font size 
legend.location.x <- 0			# Legend X location within the chart - Value ranges from zero to one
legend.location.y <- 0.05		# Legend Y location within the chart - Value ranges from zero to one

  # End of Grpahics Options

write.report <- 2		# Option 0 produces no report
  # END USER INPUT

  # KEY OUTPUT
  #  The main figure is the key output, which allows the user to determine 
  #  break-points for piece-wise linear regressions
  #  breakdate is the date where the slope of the loess curve changes sign
  
  ###################################################
  # Script code starts here
source(paste(scripts.path,"functions/defineData.R",sep="")) #call defineData.R script

  # select data for the desired time window
ytmp <- ytmp.0[ttmp.0>=start.date & ttmp.0<=end.date]
ttmp <- ttmp.0[ttmp.0>=start.date & ttmp.0<=end.date]
ytmp <- fac2num(ytmp)

# if(length(ytmp) < 5) # too few data points
# {
#   exit()
# }

source(paste(scripts.path,"functions/aggregateData.R",sep="")) #call aggregateData.R script

if (break.date > start.date) {
  break.date.tdd <- fac2num(year(break.date))+(fac2num(yeardays(break.date))-0.5)/365
  y[tdd<break.date.tdd] <- y[tdd<break.date.tdd]+offset
}

y.loess.1 <- loess(y~tdd,degree=degree.x,span=span.1)
y.loess.2 <- loess(y~tdd,degree=degree.x,span=span.2)

#  "breakpts" are the dates where the slope of the loess curve changes sign
sign.change.span.1 <- append(diff(sign(diff(y.loess.1$fitted))), 0, after = 0)
sign.change.span.2 <- append(diff(sign(diff(y.loess.2$fitted))), 0, after = 0)
breakpts.span.1 <- t[sign.change.span.1!=0]
breakpts.span.2 <- t[sign.change.span.2!=0]

breakpts.span.dates.1	<- dates.agg[sign.change.span.1!=0]
breakpts.span.dates.2	<- dates.agg[sign.change.span.2!=0]

slope.span.1 <- diff(y.loess.1$fitted)
slope.span.2 <- diff(y.loess.2$fitted)

mean.slope.span.1 = 0.0
mean.slope.span.2 = 0.0

  #  Set the initial mean.slope.span values
for (count in 1:slope.change.window)
{	mean.slope.span.1 = mean.slope.span.1 + slope.span.1[count]/slope.change.window
  mean.slope.span.2 = mean.slope.span.2 + slope.span.2[count]/slope.change.window
}

slope.change.span.1 = 0 # Assign a zero so the list can be appended to
mean.slope.span.1.vec <- rep(0,times=length(slope.span.1))

  #  Scroll through all slopes to identify sudden changes
for (count in(slope.change.window+1):length(slope.span.1))
{	if(sign(slope.span.1[count]) == sign(mean.slope.span.1) && ((abs(slope.span.1[count]) > abs(mean.slope.span.1) * slope.change.factor) 
                                                              || (abs(slope.span.1[count]) < abs(mean.slope.span.1) / slope.change.factor))) 
  slope.change.span.1 <- c(slope.change.span.1,t[count]) # a large change is observed in the slope
  
  # update the moving average	
  mean.slope.span.1 = mean.slope.span.1 + (slope.span.1[count] - slope.span.1[count-slope.change.window]) / slope.change.window
  mean.slope.span.1.vec[count] <- mean.slope.span.1
}
slope.change.span.1 <- slope.change.span.1[-1] # remove the first member (zero)

slope.change.span.2 = 0 # Assign a zero so the list can be appended to
for (count in(slope.change.window+1):length(slope.span.2))
{	if(sign(slope.span.2[count]) == sign(mean.slope.span.2) && (abs(slope.span.2[count]) > abs(mean.slope.span.2) * slope.change.factor) || (abs(slope.span.2[count]) < abs(mean.slope.span.2) / slope.change.factor)) slope.change.span.2 <- c(slope.change.span.2,t[count]) # a large change is observed in the slope
  # update the moving average	
  mean.slope.span.2 = mean.slope.span.2 + (slope.span.2[count] - slope.span.2[count-slope.change.window]) / slope.change.window
}
slope.change.span.2 <- slope.change.span.2[-1] # remove the first member (zero)

  #  Identify sudden change points
ydiff <- diff(y)

ydiff.pdslag <- diff(y,lag=n.pds)
bkpt.abrupt <- ttmp[abs(ydiff)>mean(ydiff)+slope.sd.factor*sd(ydiff)]
bkpt.abrupt.seas <- tdd[abs(ydiff.pdslag)>mean(ydiff.pdslag)+slope.sd.factor*sd(ydiff.pdslag)]

bkpt.abrupt.dates		<-	bkpt.abrupt
bkpt.abrupt.seas.dates	<-	dates.agg[bkpt.abrupt.seas != 0]

if ((mode == "D") || (mode=="Y")){
  breakpts.span.1.outformat <- t.out[sign.change.span.1!=0]
  breakpts.span.2.outformat <- t.out[sign.change.span.2!=0]
}
if ((mode == "M") || (mode=="S")){
  breakpts.span.1.outformat <- t.out[sign.change.span.1!=0,]
  breakpts.span.2.outformat <- t.out[sign.change.span.2!=0,]
}

  # define a data frame to be used for plotting the break dates on the plots
loess.frame <- data.frame(date=t,loess01=y.loess.1$fitted,loess02=y.loess.2$fitted) 

  # Match breakpts for plotting loess - place after calculating breakpts 
span.1.pts <- data.frame(date=breakpts.span.1)#,value = 1) 
match.vec <- match(span.1.pts$date,loess.frame$date) 
span.1.pts$value <- loess.frame$loess01[match.vec] 
span.2.pts <- data.frame(date=breakpts.span.2)#,value = 1)
match.vec <- match(span.2.pts$date,loess.frame$date) 
span.2.pts$value <- loess.frame$loess02[match.vec] 
abrupt.pts <- data.frame(date=bkpt.abrupt)#,value = 1)
match.vec <- match(abrupt.pts$date,loess.frame$date)
abrupt.pts$value <- y[match.vec]

slope.change.span.1.pts <- data.frame(date=slope.change.span.1)
match.vec <- match(slope.change.span.1,loess.frame$date)
slope.change.span.1.pts$value <- loess.frame$loess01[match.vec]
slope.change.span.1.dates	<- dates.agg[match.vec]

is(slope.change.span.1)

  # Confidence intervals
  #conf.1 <- confint(predict(y.loess.1, newdata=tdd, se.fit=TRUE), level=0.95) S-Plus equivalent
conf.1 <- pointwise(predict(y.loess.1, newdata=tdd, se=TRUE), coverage=0.95)

main.text <- paste("LOWESS Smoothers\n",file.name," - Data Set:",dataset.label,"     ",subset.label,sep="")

if(chart.option == 2) {
  png(paste(file = destination.path,"Breakpoint ",subset.label,"-",min(year(ttmp)),"-",
             max(year(ttmp))," ",".png", sep = ""), width = 1000, height = 700, res=100)  
  plot(t,y,type="p",pch = 22, cex = 0.3, ylab=y.label,xlab="Year",main = paste("LOESS Smoother\n",subset.label))
  lines(t,y)
  lines(t,fitted(y.loess.1),col=2) # color = 2 (red)
  lines(t,fitted(y.loess.2),col=4) # color = 4 (blue)
  points(span.1.pts$date,span.1.pts$value,type="p",pch=17,col=2,cex=2) 
  points(span.2.pts$date,span.2.pts$value,type="p",pch=18,col=4,cex=2) 
  lines(t,conf.1$upper,lty=5)
  lines(t,conf.1$lower,lty=5)
  leg.text = c(paste("Loess f = ", span.1, sep = ""), 
               paste("Loess f = ", span.2, sep = ""), 
               paste("Break f = ", span.1, sep = ""), 
               paste("Loess f = ", span.2, sep = ""), 
               "Original")
  legend("topright", leg.text, merge = FALSE, lty=c(1,1,0,0,1), cex = c(0.75,0.75,0.75,0.75,0.75),
         pch=c(NA_integer_,NA_integer_,17,18,NA_integer_), col=c(2,4,2,4,1), border=FALSE, xjust = 0)
  dev.off()
}
  # end if chart.option > 0

  # Write summary comparison results to report - if requested
output.text.file <- paste(file = destination.path,"Breakpoint ",min(year(ttmp)),"-",
                          max(year(ttmp))," ",subset.label,".txt", sep = "")

if (write.report == 1 || write.report == 2) {
  line.text <- paste("Today's date: ",date(),sep="")
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=F)
  line.text <- paste("Generated by Script: ",script.name," - ",script.version)
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  line.text <- paste("Data is read from file: ",file.name,sep="")
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  line.text <- paste("Data label in the input spreadsheet: ",dataset.label,sep="")
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  if(subset.label != "") {
    line.text <- paste("Data subset in spreadsheet: ",subset.label,sep="")
    cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  }
  line.text <- paste("Y variable label: ",y.variable.label,sep="")
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  line.text <- paste("Start date: ",start.date,"\nEnd date: ",end.date,sep="")
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  line.text <- paste("Aggregation mode: ",mode,sep="")
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  if(degree.x == 1) {
    line.text <- paste("Linear fit",sep="")
  }
  if(degree.x == 2) {
    line.text <- paste("Quadratic fit",sep="")
  }
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  line.text <- paste("First smoothing parameter: ",span.1,sep="")
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  line.text <- paste("Second smoothing parameter: ",span.2,sep="")
  cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)
  
  if(length(breakpts.span.dates.1)> 0) {
    line.text <- paste("First set of break point dates (slope sign change based on smoothing parameter=",span.1,"):",sep="")
    cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)	
    for(i in 1:length(breakpts.span.dates.1)){
      line.text <- paste(i,"  ",breakpts.span.dates.1[i],sep="")
      cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)	
    }
  }
  
  if(length(breakpts.span.dates.2) > 0) {
    line.text <- paste("First set of break point dates (slope sign change based on smoothing parameter=",span.2,"):",sep="")
    cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)	
    for(i in 1:length(breakpts.span.dates.2)){
      line.text <- paste(i,"  ",breakpts.span.dates.2[i],sep="")
      cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)	
    }
  }
  
  if(length(bkpt.abrupt.dates) > 0) {
    line.text <- paste("Datum shift break point dates (extreme instantaneous slope based on smoothing parameter=",span.1,"):",sep="")
    cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)	
    for(i in 1:length(bkpt.abrupt.dates)){
      line.text <- paste("  ",bkpt.abrupt.dates[i],sep="")
      cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)	
    }
  }
  
  if(length(slope.change.span.1.dates) > 0) {
    line.text <- paste("Slope value change break point dates (based on smoothing parameter=",span.1,"):",sep="")
    cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)	
    for(i in 1:length(slope.change.span.1.dates)){
      line.text <- paste("  ",slope.change.span.1.dates[i],sep="")
      cat(line.text, file=output.text.file, sep="\n", fill=F, labels=NULL, append=T)	
    }
  }
  
  if (write.report == 1) {
    guiOpen( "Script",FileName = output.text.file,Hide = F,Show = "Normal",Top = "Auto",Left = "Auto",Width = "1113",Height = "787")
  }
}
}